version: "3.8"

services:
  calculator:
    build:
      context: ./calculator
    ports:
      - "8000:8000"
    restart: unless-stopped

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped